FROM python:3.10

WORKDIR /audit_alpes-real-estate

COPY . .

RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN python -m pip install pulsar-client


EXPOSE 8008

CMD [ "flask", "--app", "app/api", "run", "--host=0.0.0.0", "--port", "8008", "--reload"]