version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-stage
    container_name: audit_alpes-real-estate
    restart: unless-stopped
    ports:
      - '8008:8008'
    volumes:
      - .:/audit_alpes-real-estate
    networks:
      internal_net:
        aliases:
          - local.audit_alpes-real-estate
    depends_on:
      - postgresql

  postgresql:
    image: postgres:15
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=6565
      - POSTGRES_DB=estates_alpes_real_estate
    networks:
      internal_net:
        aliases:
          - local.postgres

networks:
  internal_net:
    driver: bridge
    name: internal_net

volumes:
  postgres-data:
